#!/bin/sh
exec 2>&1
#
# QMQP service 
#
USER=qmaild
QMAIL=/var/qmail
ME=$(head -1 $QMAIL/control/me)

PATH=$PATH:"$QMAIL/bin"

# source the environemt in ./env
eval `env - envdir ./env '\
        BEGIN { for (i in ENVIRON) printf "%s=\"%s\"\n", i, ENVIRON[i] }'`

exec envdir ./env \
	envuidgid $USER \
	tcpserver -v -URl $ME -x$QMAIL/control/qmail-qmqpd.cdb \
	    ${CONCURRENCY+"-c$CONCURRENCY"} ${BACKLOG+"-b$BACKLOG"} 0 628 \
	$QMAIL/bin/qmail-qmqpd

