#!/bin/sh
exec 2>&1
#
# SMTP service 
#
USER=qmaild
QMAIL=/var/qmail
ME=$(head -1 $QMAIL/control/me)
CONCURRENCY=${CONCURRENCY:=50}

PATH=$PATH:"$QMAIL/bin"

/* source the environemt in ./env */
eval `env - envdir ./env env`

exec envdir ./env \
	envuidgid $USER \
	tcpserver -v -URl $ME -x$QMAIL/control/qmail-smtpd.cdb \
	    ${CONCURRENCY+"-c$CONCURRENCY"} ${BACKLOG+"-b$BACKLOG"} 0 smtp \
	$QMAIL/bin/pbscheck \
	$QMAIL/bin/qmail-smtpd

